### ISSUE TITLE
presence channel member added, how to know easily which member is new?

### ISSUE THREAD

**Issue by cherrr** [pusher-community/pusher-websocket-dotnet#15]
The librairy offers a list of all current member. However I need to know which one joined it. Subscribed to Added Member function, I can't find an item which returns me this value? I only have access to all present members:

``` csharp
static void _presenceChannel_MemberAdded(object sender)
{
    foreach (var mem in _presenceChannel.Members)
```

So I figured I could bind on the event when one member joined, but it is not triggered (I believe this is because your librairy intercepts this event already?)

``` csharp
_presenceChannel.Bind("pusher_internal:member_added", (dynamic mem) =>
{
```

So far, unless there is a simple way I will need to always have a copy of the array of present members, and always compare it to the new members list on _presenceChannel_MemberAdded

However it seems like to much for what it does. Is there a way already to access it? If not I think it would be a nice adding. For now I'm using the last method mentionned.

Thanks

**Comment by alexbooker** [comment]
Hi,

I'm about to sign off but just to let you know, I've read your issue and I'll look into it tomorrow for you.

**Comment by cherrr** [comment]
thanks a lot, if you have questions about it, I can give more details. If I may suggest, just having an array that contains the members added (like the Members array), I think it would be practical. I could use such an array in the added member event, and I could keep it or delete it from the said array. Same would go for the member removed?

**Comment by alexbooker** [comment]
Hi again, @cherrr

I think you're observation right: `pusher_internal:member_added` and `pusher:member_added` aren't raised because they are intercepted by the `MemberAdded` event. Thing is, `MemberAdded `Yes, so when the `MemberAdded` event is raised, only the `sender` is passed: 
```csharp
internal void AddMember(string data)
{
    var member = ParseMember(data);
     if (!Members.ContainsKey(member.Key))
         Members.Add(member.Key, member.Value);
     else
          Members[member.Key] = member.Value;
       if (MemberAdded != null)
           MemberAdded(this);
 }
```

As you can see, the member who just joined's `data` is available and should therefore be simple to pass with the event, which is a good thing.

**Comment by alexbooker** [comment]
Hi again @cherrr,

I think your observation right - `pusher_internal:member_added` isn't raised because it's intercepted by the `MemberAdded` event. Thing is, `MemberAdded ` is only passed the sender (`this`) and not data about the member who just joined, even though it's available in the same context:

```csharp
internal void AddMember(string data)
{
    var member = ParseMember(data);
     if (!Members.ContainsKey(member.Key))
         Members.Add(member.Key, member.Value);
     else
          Members[member.Key] = member.Value;
       if (MemberAdded != null)
           MemberAdded(this);
 }
```

Going forward, would it solve your problem to pass that data along with the event, thus that you could write:

```csharp
channel.MemberAdded += (sender, memberData) =>
{
};
```

`memberData` would be data about the member that just joined.

**Comment by cherrr** [comment]
that would totally solver it!! Right now I'm making an array to filter it, but this would make current code much efficient!! If you do so, please let me know when I need to fetch dll again to have it!! it's gonna save useless loops!!

**Comment by alexbooker** [comment]
Hi,

I just committed https://github.com/pusher-community/pusher-websocket-dotnet/commit/205930b1b2979ddadcadb3e4d6795e48aa1dc2f8, which should solve your problem.

Note that the NuGet package hasn't been updated yet but I'll be updating it soon.

**Comment by cherrr** [comment]
Thanks a lot!! from what I look, it should do the trick. Is there a way to be warned when NuGet package gets updated or I have to check back?

**Comment by alexbooker** [comment]
I'll make sure to ping you here when it's live (hopefully tomorrow!)

**Comment by cherrr** [comment]
Hi there!!

I wonder if this has been fixed or if it's still planned? If it's aborted, I'll make a workaround. Same for my other issue.

Thanks!!

**Comment by hot-leaf-juice** [comment]
@cherrr this change is live as of version 0.4.0
